### ISSUE TITLE
StarRatingModule is not an NgModule

### ISSUE THREAD

**Issue by athoma13** [BioPhoton/angular-star-rating#5]
ERROR in StarRatingModule is not an NgModule

When compiling with WebPack.
Using angular-cli.
used npm to install angular-star-rating

my app.module.ts looks like this:
import { StarRatingModule } from 'angular-star-rating/src/star-rating.module';

@NgModule({
  declarations: [
    AppComponent, ProductTileComponent
  ],
  imports: [
    BrowserModule,
    FormsModule,
    HttpModule,
    MaterialModule.forRoot(),
    StarRatingModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }

**Comment by ianchute** [comment]
@athoma13  Have you found a solution for this? I was able to use the component successfully for a few days. When I reinstalled all my nodules in a different machine it doesn't seem to work anymore.

@BioPhoton Hope you can help us :(

**Comment by ianchute** [comment]
I was able to _workaround_ the problem by doing the following:

1. `rm -rf node_modules/angular-star-rating/node_modules`
2. comment out line 15 (moduleId: module.id) of node_modules\angular-star-rating\src\star-rating.component.ts

**Comment by athoma13** [comment]
Nope,

I gave up on this... created my own. (which isn't as versatile, but does
the job for what I needed)...

**Comment by BioPhoton** [comment]
Hi, @athoma13, @ianchute!

Sry for my long delay. I was on a log trip....

I released a new version. Also the docs are updated. And i added and updated example folder which shows the usage in code. 

This update should alse solve #4 as my example is created with the latest cli.

Please let me know if it works now.

**Comment by Zoly90** [comment]
I just checked it, I had to download the zip version and put it manually in the node_modules folder.
So it did not work with the npm install version. But unfortunately it is still not working by using the star-rating-comp tag, it is obvious that something is there and you can see it in inspect too but there is nothing on the browser (using Chrome).
On the other hand, the css version of this project works pretty good, but it is a little hard to work with. But the interactive part is not working :(
I hope you will be able to resolve the issue

**Comment by BioPhoton** [comment]
Hi @Zoly90 ,
I'm not sure why your npm install is not working. if i do ```npm install angular-star-rating@2.0.0-rc.5 --save``` everything is in the ```node_modules/angular-star-rating``` folder.

The other problem "invisible component" is that you forgot to copy the star icons into your assets folder.

I updated the [install guide](https://github.com/BioPhoton/angular-star-rating/blob/master/README.MD#consuming-the-library). Please check it out here and give me feedback about the text and if it is detailed enough to follow.

Thx for your time!

Best,
Michael

**Comment by Zoly90** [comment]
Thank you for your advice @BioPhoton, but unfortunately it is still invisible :(. Maybe I will be able to make it work at a later time.
Best of all,
Zoli

**Comment by BioPhoton** [comment]
Hi @athoma13. 

As i described in the readme you can import the library as follow:

```typescript

// IMPORT YOUR LIBRARY
import { StarRatingModule } from 'angular-star-rating';
  
@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
  
    // SPECIFY YOUR LIBRARY AS AN  IMPORT
    StarRatingModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

**Comment by BioPhoton** [comment]
I updated the docs once more. Guess it's pretty clear now. Also 2.0.0 is out, so i will close it.
Feel free to reopen the issue.
