### ISSUE TITLE
Not filling up more than 5 stars

### ISSUE THREAD

**Issue by Parez** [BioPhoton/angular-star-rating#61]
## I'm submitting a...

<pre><code>
[x] Bug report  
[ ] Feature request
</code></pre>

## Current behavior

When I make an input [rating]="some value greater than 5" [numOfStars]="10" only 5 stars are getting filled.

## Expected behavior

All stars up to the value should be filled, obviously.

## Environment

<pre><code>
Library version: 3.0.8
Angular version: 5.0.0

<star-rating-comp class="movie-rating" [starType]="'svg'"
                      [numOfStars]="10"
                      [showHalfStars]="true"
                      [hoverEnabled]="true"
                      [rating]="movie.imdbRating-5+5"
                      (onClick)="onRate($event)">
    </star-rating-comp>
Browser:

- [x] Chrome (desktop) version XX
</code></pre>

**Comment by BioPhoton** [comment]
Hi @Parez ! 
Thx for the issue! I forgot to mentions that there is a setting in the scss file...
[maxNumOfStars](https://github.com/BioPhoton/css-star-rating/blob/master/src/scss/_variables.scss#L8)
You can easily override this number over the scss vars and done.

I have to update the docs with this information. 

I hope it helps. 

best,
Michael

**Comment by visibleajay** [comment]
HI @BioPhoton,

Thanks for providing us a beautiful star rating application.

I am using star rating in my application but maximum no of stars getting selected is only 5. I have checked it by overriding the var in css-star-rating.css variable file and also by creating the same var in styles.scss file. Though I am just updating a single variable maxNumOfStars. 

Any Help is Appreciated.

Regards
Ajay

**Comment by ghost** [comment]
Same problem here. Hope this can be resolved.

**Comment by BioPhoton** [comment]
Did you try to do it like this?

https://github.com/BioPhoton/angular-star-rating/wiki/Customizing-Styles

**Comment by ghost** [comment]
> Did you try to do it like this?
https://github.com/BioPhoton/angular-star-rating/wiki/Customizing-Styles

Thanks for your answer @BioPhoton this is how my code looks like. I'm using Angular 5 btw

```scss
$maxNumOfStars: 10;
@import "~angular-star-rating/assets/scss/star-rating";
```
```HTML
<star-rating-comp
    [id]="'album-rating'"
    [starType]="'svg'"
    [rating]="2.63"
    [staticColor]="'ok'"
    [hoverEnabled]="true"
    [size]="'large'"
    [step]="0.5"
    [showHalfStars]="true"
    [numOfStars]="10"
    [readOnly]="false"
    [rating]="3">
</star-rating-comp>
```

**Comment by BioPhoton** [comment]
Hmm, try to import from css-star-rating

**Comment by ghost** [comment]
I don't know what import you mean exactly. The scss should be loaded correctly since the stars are all displayed, only the behaviour is odd at times.

EDIT: I guess you meant your other repo BioPhoton/css-star-rating and link to the star-rating.scss there?

EDIT2: I copied the scss files to a local folder and imported them like this:
```SCSS
$maxNumOfStars: 10;
// @import "~angular-star-rating/assets/scss/star-rating";
@import "./star-rating/scss/star-rating";
```

Still the same behaviour.

**Comment by BioPhoton** [comment]
Did it work with the other import path?

**Comment by ghost** [comment]
Sadly it didn't. I edited my previous comment before with more info.

**Comment by BioPhoton** [comment]
Strange... The color override works. Will check it...
Thx for your time!

**Comment by ghost** [comment]
Thanks mate!

**Comment by gulamabbas** [comment]
Having the same issue, any updates about it?

**Comment by samuelna** [comment]
Tried the css override. Having same trouble as others. Any rating value over 5 are not fully filled to that value.

Did bit of experimenting. Went into `node_modules/angular-star-rating/index.js` and modified the `this.numOfStars` to the desired number and it worked. But don't know how to change that config in app component so the change always get overwritten when doing `npm install`

**Comment by todorivanov** [comment]
I'm having the same issue. It seems to be happening when using an NgFor or some iterations. If you use the component outside any iterations it works okay.

EDIT: Well, apparently sometimes the change detection doesn't go as planned and the `numOfStars` property is not changed properly.

**Comment by todorivanov** [comment]
@BioPhoton I've placed a Pull Request with a fix for this bug, you can check it out here
[HERE](https://github.com/BioPhoton/angular-star-rating/pull/75)

**Comment by BioPhoton** [comment]
THX @todorivanov for investing time and energy into this bug!! <3
I will give it a try on the weekend!

**Comment by todorivanov** [comment]
@BioPhoton Any news on it?

**Comment by BioPhoton** [comment]
Should be fixed in the latest version. I set the default number if start to 13.
I also created a demo, you can test it [here](https://biophoton.github.io/angular-star-rating).

More stars can be accomplished by editing the css-star-rating lib

**Comment by allout58** [comment]
Issue is still not resolved for hovering stars. css-star-rating does not mark maxNumOfStars as default, so setting the variable before importing the library does not work as expected. I have submitted a PR to css-star-rating to remedy this.
